//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEbtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctpn
    {
        public string IDPN { get; set; }
        public string IDSP { get; set; }
        public int SLNHAP { get; set; }
        public int DONGIANHAP { get; set; }
    
        public virtual phieunhap phieunhap { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
