//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEbtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public hoadon()
        {
            this.cthds = new HashSet<cthd>();
        }
    
        public int IDHD { get; set; }
        public int IDUSER { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string GHICHU { get; set; }
        public string IDNV { get; set; }
    
        public virtual ICollection<cthd> cthds { get; set; }
        public virtual nguoidung nguoidung { get; set; }
    }
}
