//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEbtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        public nguoidung()
        {
            this.hoadons = new HashSet<hoadon>();
        }
    
        public int IDUSER { get; set; }
        public string IDVAITRO { get; set; }
        public string HOTEN { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string MK { get; set; }
        public string GIOITINH { get; set; }
        public string AVATAR { get; set; }
    
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual vaitro vaitro { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
