//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEbtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhacc
    {
        public nhacc()
        {
            this.phieunhaps = new HashSet<phieunhap>();
        }
    
        public string IDNCC { get; set; }
        public string TENNCC { get; set; }
    
        public virtual ICollection<phieunhap> phieunhaps { get; set; }
    }
}
