//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEbtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public sanpham()
        {
            this.cthds = new HashSet<cthd>();
            this.ctpns = new HashSet<ctpn>();
        }
    
        public string IDSP { get; set; }
        public string IDTHUONGHIEU { get; set; }
        public string IDLOAI { get; set; }
        public string TENSP { get; set; }
        public string ANHSP { get; set; }
        public int GIATIEN { get; set; }
        public string DONVITINH { get; set; }
        public int SLTON { get; set; }
        public string IDTINHTRANG { get; set; }
        public int THOIHANBH { get; set; }
        public string MOTA { get; set; }
    
        public virtual ICollection<cthd> cthds { get; set; }
        public virtual ICollection<ctpn> ctpns { get; set; }
        public virtual loai loai { get; set; }
        public virtual tinhtrang tinhtrang { get; set; }
        public virtual thuonghieu thuonghieu { get; set; }
    }
}
