//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEbtinhoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaitro
    {
        public vaitro()
        {
            this.nguoidungs = new HashSet<nguoidung>();
        }
    
        public string IDVAITRO { get; set; }
        public string TENVAITRO { get; set; }
        public bool DANGNHAP { get; set; }
        public bool HOADON { get; set; }
        public bool NGUOIDUNG { get; set; }
        public bool SANPHAM { get; set; }
    
        public virtual ICollection<nguoidung> nguoidungs { get; set; }
    }
}
