//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieunhap
    {
        public phieunhap()
        {
            this.ctpns = new HashSet<ctpn>();
        }
    
        public string IDPN { get; set; }
        public string IDNV { get; set; }
        public string IDNCC { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
    
        public virtual ICollection<ctpn> ctpns { get; set; }
        public virtual nhacc nhacc { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
